In [1]:
import numpy as np

# 一: 创建Array

### 构造

1. np.array(list)

#### array 优先级
np.array 会强制类型统一, 优先级如下:

str > float > int


In [2]:
names = ['tom','lucy']

arr1 = np.array(names)

In [7]:
np.ones(shape=(3,))

array([1., 1., 1.])

In [9]:
np.ones(shape=(1,3))

array([[1., 1., 1.]])

In [8]:
np.ones(shape=(3,1))

array([[1.],
       [1.],
       [1.]])

In [10]:
np.full(shape=(2,3), fill_value=6)

array([[6, 6, 6],
       [6, 6, 6]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
## 随机整数
np.random.randint(0,10,size=(3,2))

array([[2, 3],
       [5, 3],
       [8, 5]])

In [14]:
## 随机标准正态分布
np.random.randn(3,2)

array([[-0.18663644, -1.17510708],
       [-1.99193088,  0.57615073],
       [ 0.27039054, -0.68894006]])

In [16]:
## 随机普通正态分布
np.random.normal(loc = 170, scale = 5, size = (3,2))

array([[177.83637685, 166.49295762],
       [170.31657825, 165.98569822],
       [174.29592966, 166.1753696 ]])

In [17]:
## 0-1的小数
np.random.random(size=(3,2))

array([[0.3167279 , 0.33114595],
       [0.61732059, 0.68648846],
       [0.52427397, 0.68599471]])

In [18]:
## 生成一组随机索引
np.random.permutation(10)

array([6, 7, 0, 5, 3, 1, 9, 4, 2, 8])

# 二: ndarray 的属性

## 4个属性:
1. ndim: 维度
2. shape: 形状
3. size: 总长度
4. dtype: 元数类型

In [19]:
arr = np.random.randint(0,100,size=(5,4,3))

In [20]:
arr.ndim

3

In [21]:
arr.shape

(5, 4, 3)

In [23]:
arr.size

60

In [24]:
arr.dtype

dtype('int32')

In [25]:
type(arr)

numpy.ndarray

# 三: ndarray 的基本操作

## 1. 索引
## 2. 切片
## 3. 变形
## 4. 级联
## 5. 副本

# 四: ndarray 的聚合操作

 1. arr.sum()
 2. arr.max()/min()
 3. arr.mean()
 4. arr.argmin()/argmax()
 5. 方差: arr.var()
 6. 标准差: arr.std()
 7. 中位数: np.median(arr)
 8. 分位数: np.percentile(data, [0.25, 0.5, 0.75])


1. arr.any() , 有一个 true 就返回 true
2. arr.all() , 全是 true 才返回 true

## 矩阵乘法
np.dot(arr1, arr2)